### ISSUE TITLE
[이주용] 이미지 조회 관련 html, js 파일 작성

### ISSUE THREAD

**Issue by Juyong226** [Juyong226/gbCollector#114]
SWI.html 작성
SWI.js 작성
-사진을 찍어 이미지를 업로드하면 즉시 서버로 이미지 분석 요청을 보냄(base64로 이미지 파일 인코딩)
-분석 결과 이미지를 화면에 노출
-'배출방법조회' 버튼을 누를 시, 이미지 분석에서 받은 쓰레기 분류 키워드를 다시 서버로 보내 배출방법을 조회함
-사용자가 직접 키워드를 검색할 수 있도록 코드 재활용
-TTS 적용

**Comment by Freemill** [comment]
굿굿
