### ISSUE TITLE
[이주용] logout 문제 해결 / html 파일 이동 / 파일 이름 수정

### ISSUE THREAD

**Issue by Juyong226** [Juyong226/gbCollector#120]
login.js 파일 수정 및 추가
- 쿠키 삭제 시 path를 추가 기입하여 도메인 어디서든 삭제가 되도록 함
- fn_isLogined, fn_checkSession 함수로 화면 재로드시 세션 유효성 검사

MemberController 파일 수정 및 추가
- 로그아웃 요청 시 session 만료 검사
- checkSession 메서드 작성

html파일들
- 하단 바에 카메라 이미지 삽입하고 SWI.thml과 링크
- sample_index.html ->> index.html / sample_swv.html ->> SWV.html 로 파일명 변경
- index.html 파일을 제외하고 모든 html파일들 html폴더로 이동

일부 파일 삭제
- style.css
- scripts.js
- 복사되었던 trashCanMap.html, zeroWasteShopMap.html

**Comment by Freemill** [comment]
굿굿
